# Generated by Django 5.1.1 on 2024-09-19 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100)),
                ('modal', models.CharField(max_length=100)),
                ('showroom_price', models.CharField(max_length=100)),
                ('on_road_price', models.CharField(max_length=100)),
            ],
        ),
    ]
